export const COMMAND_IDS = {
  changeComparisonMode: "refhaven.changeComparisonMode",
  changeFileAnnotations: "refhaven.changeFileAnnotations",
  closeComparison: "refhaven.closeComparison",
  compareFileWithRevision: "refhaven.compareFileWithRevision",
  compareCurrentBranch: "refhaven.compareCurrentBranch",
  compareBranchWithCurrent: "refhaven.compareBranchWithCurrent",
  copyBranchName: "refhaven.copyBranchName",
  copyCommitMessage: "refhaven.copyCommitMessage",
  copyCommitSha: "refhaven.copyCommitSha",
  copyComparisonSummary: "refhaven.copyComparisonSummary",
  copyFilePath: "refhaven.copyFilePath",
  copyRelativeFilePath: "refhaven.copyRelativeFilePath",
  copyStashMessage: "refhaven.copyStashMessage",
  copyWorktreePath: "refhaven.copyWorktreePath",
  openFileHistoryAtRevision: "refhaven.openFileHistoryAtRevision",
  openFileHistoryDiff: "refhaven.openFileHistoryDiff",
  openLineDiff: "refhaven.openLineDiff",
  newComparison: "refhaven.newComparison",
  openChangedFileAtRevision: "refhaven.openChangedFileAtRevision",
  openFile: "refhaven.openFile",
  openFileAtRevision: "refhaven.openFileAtRevision",
  openFileDiff: "refhaven.openFileDiff",
  openWorktree: "refhaven.openWorktree",
  pinComparison: "refhaven.pinComparison",
  refreshAll: "refhaven.refreshAll",
  refreshComparison: "refhaven.refreshComparison",
  refreshFileHistory: "refhaven.refreshFileHistory",
  refreshRepositoryNavigation: "refhaven.refreshRepositoryNavigation",
  refreshStashes: "refhaven.refreshStashes",
  searchCommits: "refhaven.searchCommits",
  showCommitDetails: "refhaven.showCommitDetails",
  showFileHistory: "refhaven.showFileHistory",
  showLineBlameActions: "refhaven.showLineBlameActions",
  showLineHistory: "refhaven.showLineHistory",
  showRefHavenMenu: "refhaven.showRefHavenMenu",
  swapComparison: "refhaven.swapComparison",
  toggleInlineBlame: "refhaven.toggleInlineBlame",
  unpinComparison: "refhaven.unpinComparison",
  viewFilesAsList: "refhaven.viewFilesAsList",
  viewFilesAsTree: "refhaven.viewFilesAsTree",
} as const;

export type CommandId = (typeof COMMAND_IDS)[keyof typeof COMMAND_IDS];
