import assert from "node:assert/strict";

import { COMMAND_IDS } from "../../src/ui/commands/commandIds";

suite("command identifiers", () => {
  test("exposes the complete command set", () => {
    assert.deepEqual(COMMAND_IDS, {
      changeComparisonFileFilter: "refhaven.changeComparisonFileFilter",
      changeComparisonFileSort: "refhaven.changeComparisonFileSort",
      changeComparisonMode: "refhaven.changeComparisonMode",
      changeFileAnnotations: "refhaven.changeFileAnnotations",
      changeFileHistoryFilter: "refhaven.changeFileHistoryFilter",
      changeLineIntelligence: "refhaven.changeLineIntelligence",
      changeStashFilter: "refhaven.changeStashFilter",
      closeComparison: "refhaven.closeComparison",
      compareSelectedBranches: "refhaven.compareSelectedBranches",
      compareCommitWithParent: "refhaven.compareCommitWithParent",
      compareStashFileWithHead: "refhaven.compareStashFileWithHead",
      compareStashFileWithWorkingTree: "refhaven.compareStashFileWithWorkingTree",
      compareFileWithRevision: "refhaven.compareFileWithRevision",
      compareBranchWithCurrent: "refhaven.compareBranchWithCurrent",
      compareCurrentBranch: "refhaven.compareCurrentBranch",
      configureBrowserOrigin: "refhaven.configureBrowserOrigin",
      copyBranchName: "refhaven.copyBranchName",
      copyCommitMessage: "refhaven.copyCommitMessage",
      copyCommitSha: "refhaven.copyCommitSha",
      copyCommitDetail: "refhaven.copyCommitDetail",
      copyComparisonPatch: "refhaven.copyComparisonPatch",
      copyComparisonSummary: "refhaven.copyComparisonSummary",
      copyBrowserBranchUrl: "refhaven.copyBrowserBranchUrl",
      copyBrowserCommitUrl: "refhaven.copyBrowserCommitUrl",
      copyBrowserComparisonUrl: "refhaven.copyBrowserComparisonUrl",
      copyBrowserFileUrl: "refhaven.copyBrowserFileUrl",
      copyBrowserProjectUrl: "refhaven.copyBrowserProjectUrl",
      copyFilePatch: "refhaven.copyFilePatch",
      copyFilePath: "refhaven.copyFilePath",
      copyRelativeFilePath: "refhaven.copyRelativeFilePath",
      copyStashMessage: "refhaven.copyStashMessage",
      copyStashSha: "refhaven.copyStashSha",
      copyWorktreePath: "refhaven.copyWorktreePath",
      findOtherStashesContainingFile: "refhaven.findOtherStashesContainingFile",
      inspectCurrentLine: "refhaven.inspectCurrentLine",
      markAllComparisonFilesReviewed: "refhaven.markAllComparisonFilesReviewed",
      markFileReviewed: "refhaven.markFileReviewed",
      markFileUnreviewed: "refhaven.markFileUnreviewed",
      nextUnreviewedFile: "refhaven.nextUnreviewedFile",
      newComparison: "refhaven.newComparison",
      openAllComparisonChanges: "refhaven.openAllComparisonChanges",
      openChangedFileAtRevision: "refhaven.openChangedFileAtRevision",
      openFile: "refhaven.openFile",
      openFileAtRevision: "refhaven.openFileAtRevision",
      openFileHistoryAtRevision: "refhaven.openFileHistoryAtRevision",
      openFileHistoryDiff: "refhaven.openFileHistoryDiff",
      openNextFileHistoryRevision: "refhaven.openNextFileHistoryRevision",
      openPreviousFileHistoryRevision: "refhaven.openPreviousFileHistoryRevision",
      openCommitParentDetails: "refhaven.openCommitParentDetails",
      openBrowserBranch: "refhaven.openBrowserBranch",
      openBrowserCommit: "refhaven.openBrowserCommit",
      openBrowserComparison: "refhaven.openBrowserComparison",
      openBrowserFile: "refhaven.openBrowserFile",
      openBrowserLocalReference: "refhaven.openBrowserLocalReference",
      openBrowserProject: "refhaven.openBrowserProject",
      openBrowserReference: "refhaven.openBrowserReference",
      openLineDiff: "refhaven.openLineDiff",
      openStashFileAtRevision: "refhaven.openStashFileAtRevision",
      openWorktree: "refhaven.openWorktree",
      openFileDiff: "refhaven.openFileDiff",
      pinComparison: "refhaven.pinComparison",
      previousUnreviewedFile: "refhaven.previousUnreviewedFile",
      quickOpenComparisonFile: "refhaven.quickOpenComparisonFile",
      refreshAll: "refhaven.refreshAll",
      refreshComparison: "refhaven.refreshComparison",
      refreshFileHistory: "refhaven.refreshFileHistory",
      refreshRepositoryNavigation: "refhaven.refreshRepositoryNavigation",
      refreshStashes: "refhaven.refreshStashes",
      renameComparison: "refhaven.renameComparison",
      resetComparisonReview: "refhaven.resetComparisonReview",
      revealFileInComparison: "refhaven.revealFileInComparison",
      saveComparisonPatch: "refhaven.saveComparisonPatch",
      searchCommits: "refhaven.searchCommits",
      showCommitDetails: "refhaven.showCommitDetails",
      showStashCommitDetails: "refhaven.showStashCommitDetails",
      showFileHistory: "refhaven.showFileHistory",
      showLineBlameActions: "refhaven.showLineBlameActions",
      showLineHistory: "refhaven.showLineHistory",
      showRefHavenMenu: "refhaven.showRefHavenMenu",
      stashFile: "refhaven.stashFile",
      swapComparison: "refhaven.swapComparison",
      toggleInlineBlame: "refhaven.toggleInlineBlame",
      unpinComparison: "refhaven.unpinComparison",
      viewFilesAsList: "refhaven.viewFilesAsList",
      viewFilesAsTree: "refhaven.viewFilesAsTree",
    });
  });
});
