import assert from "node:assert/strict";

import { COMMAND_IDS } from "../../src/ui/commands/commandIds";

suite("command identifiers", () => {
  test("exposes the complete command set", () => {
    assert.deepEqual(COMMAND_IDS, {
      changeComparisonFileFilter: "refhaven.changeComparisonFileFilter",
      changeComparisonFileSort: "refhaven.changeComparisonFileSort",
      changeComparisonMode: "refhaven.changeComparisonMode",
      changeFileAnnotations: "refhaven.changeFileAnnotations",
      changeFileHistoryFilter: "refhaven.changeFileHistoryFilter",
      changeStashFilter: "refhaven.changeStashFilter",
      closeComparison: "refhaven.closeComparison",
      compareCommitWithParent: "refhaven.compareCommitWithParent",
      compareStashFileWithHead: "refhaven.compareStashFileWithHead",
      compareStashFileWithWorkingTree: "refhaven.compareStashFileWithWorkingTree",
      compareFileWithRevision: "refhaven.compareFileWithRevision",
      compareBranchWithCurrent: "refhaven.compareBranchWithCurrent",
      compareCurrentBranch: "refhaven.compareCurrentBranch",
      copyBranchName: "refhaven.copyBranchName",
      copyCommitMessage: "refhaven.copyCommitMessage",
      copyCommitSha: "refhaven.copyCommitSha",
      copyCommitDetail: "refhaven.copyCommitDetail",
      copyComparisonSummary: "refhaven.copyComparisonSummary",
      copyFilePath: "refhaven.copyFilePath",
      copyRelativeFilePath: "refhaven.copyRelativeFilePath",
      copyStashMessage: "refhaven.copyStashMessage",
      copyStashSha: "refhaven.copyStashSha",
      copyWorktreePath: "refhaven.copyWorktreePath",
      findOtherStashesContainingFile: "refhaven.findOtherStashesContainingFile",
      markAllComparisonFilesReviewed: "refhaven.markAllComparisonFilesReviewed",
      markFileReviewed: "refhaven.markFileReviewed",
      markFileUnreviewed: "refhaven.markFileUnreviewed",
      nextUnreviewedFile: "refhaven.nextUnreviewedFile",
      newComparison: "refhaven.newComparison",
      openChangedFileAtRevision: "refhaven.openChangedFileAtRevision",
      openFile: "refhaven.openFile",
      openFileAtRevision: "refhaven.openFileAtRevision",
      openFileHistoryAtRevision: "refhaven.openFileHistoryAtRevision",
      openFileHistoryDiff: "refhaven.openFileHistoryDiff",
      openNextFileHistoryRevision: "refhaven.openNextFileHistoryRevision",
      openPreviousFileHistoryRevision: "refhaven.openPreviousFileHistoryRevision",
      openCommitParentDetails: "refhaven.openCommitParentDetails",
      openGitLabBranch: "refhaven.openGitLabBranch",
      openGitLabCommit: "refhaven.openGitLabCommit",
      openGitLabComparison: "refhaven.openGitLabComparison",
      openGitLabFile: "refhaven.openGitLabFile",
      openGitLabLocalReference: "refhaven.openGitLabLocalReference",
      openGitLabProject: "refhaven.openGitLabProject",
      openGitLabReference: "refhaven.openGitLabReference",
      openLineDiff: "refhaven.openLineDiff",
      openStashFileAtRevision: "refhaven.openStashFileAtRevision",
      openWorktree: "refhaven.openWorktree",
      openFileDiff: "refhaven.openFileDiff",
      pinComparison: "refhaven.pinComparison",
      previousUnreviewedFile: "refhaven.previousUnreviewedFile",
      quickOpenComparisonFile: "refhaven.quickOpenComparisonFile",
      refreshAll: "refhaven.refreshAll",
      refreshComparison: "refhaven.refreshComparison",
      refreshFileHistory: "refhaven.refreshFileHistory",
      refreshRepositoryNavigation: "refhaven.refreshRepositoryNavigation",
      refreshStashes: "refhaven.refreshStashes",
      resetComparisonReview: "refhaven.resetComparisonReview",
      searchCommits: "refhaven.searchCommits",
      showCommitDetails: "refhaven.showCommitDetails",
      showStashCommitDetails: "refhaven.showStashCommitDetails",
      showFileHistory: "refhaven.showFileHistory",
      showLineBlameActions: "refhaven.showLineBlameActions",
      showLineHistory: "refhaven.showLineHistory",
      showRefHavenMenu: "refhaven.showRefHavenMenu",
      stashFile: "refhaven.stashFile",
      swapComparison: "refhaven.swapComparison",
      toggleInlineBlame: "refhaven.toggleInlineBlame",
      unpinComparison: "refhaven.unpinComparison",
      viewFilesAsList: "refhaven.viewFilesAsList",
      viewFilesAsTree: "refhaven.viewFilesAsTree",
    });
  });
});
